import React from 'react'
import FirstChart from './FirstChart'



const Page1 = () => {
  return (
    <div>
       <div className="container">
        <div className="row">
        <div className="col-9 mt-4">
        <small class='heading'>Consumer Markets</small>
        <h4>Alcoholic Drinks</h4>
        <button type="button" class="btn btn-primary" tabIndex={-1}>worldwide</button><br></br>
        <small><span class='ms-4'>HIGHLIGTHS</span><span class='ms-4'>MARKET DEFINATION</span><span class='ms-4'> IN SCOPE/OUT OF SCOPE</span><span class='ms-4'> REPORTS</span></small>
        <li><small>Revenue in the alcoholic drinks market amounts to US$1,481.00nb. the market is expected to grow gradually by 10.01%.</small></li>
        <li><small>The markets largest segmnent is the segment beer with a market valueme of US$563.01nb in 2022.</small></li>
        <li><small>In global comparison, most revenue is generated in China.</small></li>
        <li><small>In relation to total popular figures, per person revenues od US$190nb are generated in 2022.</small></li>
        <li><small>In alcoholic drink market, 6.6% of total revenue will be generated by online sales in 2022.</small></li>
        <li><small>By 2025, 40.26% of spending and 54% of volume conversion in alcoholic drinks market will be attributable out of home consumption.</small></li>
        <li><small>In alcoholic drink market, volume is expected to amounts 312,660ml by 2025. thr market for alcoholic drink is expected to be growth on 7.5%.</small></li>
        <li><small>Thee average volume for alcoholic drink market is expected to amount 35.75 L in 2022. </small></li>
        </div>
        <div className="col-3 mt-5">
        <button type="button" class="btn btn-primary dropdown-toggle btn1" data-bs-toggle="dropdown">Download</button><br></br>
        <button type="button" class="btn btn-light mt-2 btn2">Share</button>
        <button type="button" class="btn btn-light btn3 mt-2">Revenue by segment (2022)<br></br>US$1484.00bn</button>
        <button type="button" class="btn btn-light btn4 mt-2">Revenue change by segment (2022)<br></br>2.3%</button>
        </div>
        </div>
       </div>
       <div className="container  bg-white mt-4">
        <div className="row">
        <div className="col-9">
        <button type="button" class="btn btn-light button">Market <br />Alcoholic Drinks</button>
       <button type="button" class="btn btn-light button">Region <br />Worldwide</button>
       <button type="button" class="btn btn-light button">Compare to other regions +</button>
        </div>
       <div className="col-3">
       <button type="button" class="btn btn-light last button">Currency <br />USD(USS)</button>
       </div>
        </div>
        
       <li><small>Revenue in the alcoholic drinks market amounts to US$1,481.00nb. the market is expected to grow gradually by 10.01%.</small></li>
        <li><small>The markets largest segmnent is the segment beer with a market valueme of US$563.01nb in 2022.</small></li>
        <li><small>In global comparison, most revenue is generated in China.</small></li>
        <li><small>In relation to total popular figures, per person revenues od US$190nb are generated in 2022.</small></li>
        <li><small>In alcoholic drink market, 6.6% of total revenue will be generated by online sales in 2022.</small></li>
        <li><small>By 2025, 40.26% of spending and 54% of volume conversion in alcoholic drinks market will be attributable out of home consumption.</small></li>
        <li><small>In alcoholic drink market, volume is expected to amounts 312,660ml by 2025. thr market for alcoholic drink is expected to be growth on 7.5%.</small></li>
        <li><small>Thee average volume for alcoholic drink market is expected to amount 35.75 L in 2022. </small></li>
        </div>
        <div className="container  bg-white mt-4">
        <div className="row">
        <div className="col-9">
        <button type="button" class="btn btn-light button">Market <br />Alcoholic Drinks</button>
       <button type="button" class="btn btn-light button">Region <br />Worldwide</button>
       <button type="button" class="btn btn-light button">Compare to other regions +</button>
        </div>
       <div className="col-3">
       <button type="button" class="btn btn-light last button">Currency <br />USD(USS)</button>
       </div>
        </div>
        </div>
    <div className="container mt-2">
        <div className="row">
            <div className="col-10">
              <h1>Revenue</h1>
                <FirstChart/>
            </div>
            <div className="col-2">
            <h4>Overview</h4>
            <li type="none">Revenue</li>
            <li type="none">Analyst Opinion</li>
            <li type="none">Sales Channel</li>
            <li type="none">Volume</li>
            <li type="none">Price</li>
            <li type="none">Global Comparision</li>
            <li type="none">Methodology</li>
            <li type="none">Key Market indicators</li>
            </div>
        </div>
    </div>
    </div>
    
    
  )
}

export default Page1